### ISSUE TITLE
gyp ERR! stack Error: `gyp` failed with exit code: 1

### ISSUE THREAD

**Issue by lukedar** [MadLittleMods/node-usb-detection#177] opened 2023-03-01 18:07 UTC
Hi I get  the following error when I installed version 4.14.1. Ive tried installing gyp but it still persists.

```
gyp info it worked if it ends with ok
    gyp info using node-gyp@9.1.0
    gyp info using node@16.19.1 | darwin | x64
    gyp info find Python using Python version 3.11.2 found at "/usr/local/opt/python@3.11/bin/python3.11"
    gyp info spawn /usr/local/opt/python@3.11/bin/python3.11
    gyp info spawn args [
    gyp info spawn args   '/Users/lukedarham/.nvm/versions/node/v16.19.1/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'make',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/lukedarham/Documents/apps/idoru-desktop/node_modules/usb-detection/build/config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/lukedarham/.nvm/versions/node/v16.19.1/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/Users/lukedarham/.electron-gyp/4.2.12/include/node/common.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=/Users/lukedarham/.electron-gyp/4.2.12',
    gyp info spawn args   '-Dnode_gyp_dir=/Users/lukedarham/.nvm/versions/node/v16.19.1/lib/node_modules/npm/node_modules/node-gyp',
    gyp info spawn args   '-Dnode_lib_file=/Users/lukedarham/.electron-gyp/4.2.12/<(target_arch)/node.lib',
    gyp info spawn args   '-Dmodule_root_dir=/Users/lukedarham/Documents/apps/idoru-desktop/node_modules/usb-detection',
    gyp info spawn args   '-Dnode_engine=v8',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.'
    gyp info spawn args ]
    gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
    gyp ERR! configure error
    gyp ERR! stack Error: `gyp` failed with exit code: 1
    gyp ERR! stack     at ChildProcess.onCpExit (/Users/lukedarham/.nvm/versions/node/v16.19.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:284:16)
    gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
    gyp ERR! System Darwin 21.6.0
    gyp ERR! command "/Users/lukedarham/.nvm/versions/node/v16.19.1/bin/node" "/Users/lukedarham/.nvm/versions/node/v16.19.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/lukedarham/Documents/apps/idoru-desktop/node_modules/usb-detection
    gyp ERR! node -v v16.19.1
    gyp ERR! node-gyp -v v9.1.0
    gyp ERR! not ok
error Command failed with exit code 1.
```

I am running node v 16 but have tried 12 - 18 with no luck. Should node-usb be handling this as a dependancy? Also is 
Python 3 the correct version I should be using? 

Any help is much appretiated

**Comment by MadLittleMods** [comment] 2023-03-01 18:36
Duplicate of https://github.com/MadLittleMods/node-usb-detection/issues/163

**Closed by MadLittleMods** 2023-03-01 18:36 UTC
Labels: bug, macOS
