### ISSUE TITLE
Unable to install module

### ISSUE THREAD

**Issue by kaushik-pe** [MadLittleMods/node-usb-detection#14] opened 2015-09-01 10:10 UTC
I'm not able to install the module. Native files are not getting built because a header file is not defined. 

D:\fft test>npm install usb-detection
/
> usb-detection@1.2.0 install D:\fft test\node_modules\usb-detection
> node-gyp rebuild

D:\fft test\node_modules\usb-detection>if not defined npm_config_node_gyp (node
"C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\n
ode-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
  detection.cpp
  deviceList.cpp
  detection_win.cpp
C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\xlocale(336): wa
rning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc (..\src\deviceList.cpp) [D:\fft test\node_modules\usb-detection\b
uild\detection.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\xlocale(336): wa
rning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc (..\src\detection_win.cpp) [D:\fft test\node_modules\usb-detectio
n\build\detection.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\xlocale(336): wa
rning C4530: C++ exception handler used, but unwind semantics are not enabled.
Specify /EHsc (..\src\detection.cpp) [D:\fft test\node_modules\usb-detection\bu
ild\detection.vcxproj]
..\src\detection_win.cpp(5): fatal error C1083: Cannot open include file: 'atls
tr.h': No such file or directory [D:\fft test\node_modules\usb-detection\build\
detection.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe
` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\
npm\node_modules\node-gyp\lib\build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\fft test\node_modules\usb-detection
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs
\\node_modules\\npm\\bin\\npm-cli.js" "install" "usb-detection"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! usb-detection@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the usb-detection@1.2.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the usb-detection package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls usb-detection
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\fft test\npm-debug.log

**Comment by MadLittleMods** [comment] 2015-09-01 23:04
Duplicate of #13. See [my comment I made there, about getting the ATL library](https://github.com/MadLittleMods/node-usb-detection/issues/13#issuecomment-129655641).

**Closed by MadLittleMods** 2015-09-01 23:04 UTC
