### ISSUE TITLE
Don't get correct deviceAddress and busNumber

### ISSUE THREAD

**Issue by eivbsmed** [MadLittleMods/node-usb-detection#17] opened 2015-10-09 08:07 UTC
I need to get the correct deviceAddress and busNumber on device connect.
Now i get locationId: 0 and deviceAddress: 0. I guess locationId is the busNumber

In my case i have up to 8 of these devices on a Raspberry Pi2, but im not able to identify them correctly for my photo software whit out the use of the nonolith/node-usb libary (It don't have event's, but device info is much better)

{ locationId: 0,
    vendorId: 1193,
    productId: 12823,
    deviceName: 'Canon Digital Camera',
    manufacturer: 'Canon Inc.',
    serialNumber: '',
    deviceAddress: 0 }

**Comment by MadLittleMods** [comment] 2015-10-12 01:07
Duplicate of #8. Move discussion there.

**Closed by MadLittleMods** 2015-10-12 01:07 UTC
